# Site Configuration
title: CEH v13 Notas Estudio
description: Guía de Estudio para la Certificación de Hacker Ético

# GitHub
github_user: CarlesRep
repository: CEH

# Jekyll
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Defaults - IMPORTANTE: Esto hace que todos los archivos usen el layout
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude
exclude:
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md.bak